#+title: Outline-occur
#+author: Roi Martin
#+email: jroi.martin@gmail.com
#+language: en
#+options: ':t toc:t num:t author:t email:t

* Overview

Navigate the current buffer's outline using Occur.

-  Package name: =outline-occur=
-  Source code repository: [[https://github.com/jroimartin/outline-occur]]
-  Bug tracker: [[https://github.com/jroimartin/outline-occur/issues]]

* Installation

I have sent the package to the emacs-devel mailing list for review.  I
proposed two alternatives:

1. Outline-occur is a very small package that only depends on built-in
   functionalities---Outline and Occur---so, if the GNU Emacs
   maintainers think it is useful, it might make sense to include it
   in core as part of Outline.
2. If Outline-occur is not suitable for core, it could be published in
   GNU ELPA.

See the [[https://lists.gnu.org/archive/html/emacs-devel/2026-07/msg00156.html][mailing list thread]] for more details.

In the meantime, you can install Outline-occur using
~package-vc-install~:

#+begin_example
M-x package-vc-install<RET>https://github.com/jroimartin/outline-occur.git<RET>
#+end_example

* Configuration

Outline-occur depends on two variables to indentify the outline
headings in a buffer:

- ~outline-regexp~ :: Regular expression to match the beginning of a
  heading.

  Any line whose beginning matches this regexp is considered to start
  a heading.  Note that Outline mode only checks this regexp at the
  start of a line, so the regexp need not (and usually does not) start
  with '^'.

- ~outline-occur-regexp-override-alist~ :: Alist that overrides
  ~outline-regexp~ for specific major modes.

  Each element has the form =(MAJOR-MODE . REGEXP)=.  =MAJOR-MODE= is
  a symbol, a list of symbols or a regexp that matches the major mode
  name.  =REGEXP= is a regexp that matches the beginning of the
  outline headings in that major mode.  Any line whose beginning
  matches this regexp is considered to start a heading.  As Outline
  mode does with ~outline-regexp~, Outline-occur only checks this
  regexp at the start of a line, so the regexp need not (and usually
  does not) start with '^'.

A custom configuration is usually not required because many major
modes already set the ~outline-regexp~ variable.

* Usage

Outline-occur has a single entrypoint:

- ~outline-occur~ :: Navigate the current buffer's outline using
  Occur.

I recommend you to bind this command to =M-s M-o=.  For instance,

#+begin_src emacs-lisp
  (keymap-global-set "M-s M-o" #'outline-occur)
#+end_src
