#+title: Outline-occur
#+author: Roi Martin
#+email: jroi.martin@gmail.com
#+language: en
#+options: ':t toc:t num:t author:t email:t

*⚠️ DEPRECATED: Moved to GNU Emacs Core*

Outline-occur is now part of GNU Emacs core.  Therefore, this
repository has been archived and is now read-only.

Note that its API changed during integration into core.  Please refer
to the docstring of =outline-occur= for up-to-date documentation.

For more information, see the following commits:

- [[https://cgit.git.savannah.gnu.org/cgit/emacs.git/commit/?id=8a88f3ed5aeece4a7c8edbebc83ed52479fbbfab][8a88f3ed5aee]] "Add `outline-occur' command and `display-buffer-default-alist' variable"
- [[https://cgit.git.savannah.gnu.org/cgit/emacs.git/commit/?id=9e6f03993b824b69d7946b0e23850383d8cd3a72][9e6f03993b82]] "* lisp/outline.el (outline-occur): Autoload."

* Overview

Navigate the current buffer's outline using Occur.

-  Package name: =outline-occur=
-  Source code repository: [[https://github.com/jroimartin/outline-occur]]
-  Bug tracker: [[https://github.com/jroimartin/outline-occur/issues]]

* Installation

Install Outline-occur using ~package-vc-install~:

#+begin_example
M-x package-vc-install<RET>https://github.com/jroimartin/outline-occur.git<RET>
#+end_example

* Configuration

Outline-occur depends on two variables to identify the outline
headings in a buffer:

- ~outline-regexp~ :: Regular expression to match the beginning of a
  heading.

  Any line whose beginning matches this regexp is considered to start
  a heading.  Note that Outline mode only checks this regexp at the
  start of a line, so the regexp need not (and usually does not) start
  with '^'.

- ~outline-occur-regexp-override-alist~ :: Alist that overrides
  ~outline-regexp~ for specific major modes.

  Each element has the form =(MAJOR-MODE . REGEXP)=.  =MAJOR-MODE= is
  a symbol, a list of symbols or a regexp that matches the major mode
  name.  =REGEXP= is a regexp that matches the beginning of the
  outline headings in that major mode.  Any line whose beginning
  matches this regexp is considered to start a heading.  As Outline
  mode does with ~outline-regexp~, Outline-occur only checks this
  regexp at the start of a line, so the regexp need not (and usually
  does not) start with '^'.

A custom configuration is usually not required because many major
modes already set the ~outline-regexp~ variable.

* Usage

Outline-occur has a single entry point:

- ~outline-occur~ :: Navigate the current buffer's outline using
  Occur.

Consider binding this command to =M-s M-o=.  For instance,

#+begin_src emacs-lisp
  (keymap-global-set "M-s M-o" #'outline-occur)
#+end_src
